### ISSUE TITLE
Intermittent NLOpt error

### ISSUE THREAD

**Issue by andyreagan** [dmbates/MixedModels.jl#101]
I sometimes get the following error and I can't see to nail down what is causing it:

```
ERROR: ArgumentError: invalid NLopt arguments
Stacktrace:
 [1] chk(::Int32) at /Users/mm51929/.julia/v0.6/NLopt/src/NLopt.jl:259
 [2] chkn at /Users/mm51929/.julia/v0.6/NLopt/src/NLopt.jl:277 [inlined]
 [3] initial_step!(::NLopt.Opt, ::Array{Float64,1}) at /Users/mm51929/.julia/v0.6/NLopt/src/NLopt.jl:365
 [4] NLopt.Opt(::MixedModels.OptSummary{Float64}) at /Users/mm51929/.julia/v0.6/MixedModels/src/types.jl:146
 [5] #fit!#58(::Bool, ::Bool, ::Function, ::MixedModels.GeneralizedLinearMixedModel{Float64}) at /Users/mm51929/.julia/v0.6/MixedModels/src/PIRLS.jl:215
 [6] fit!(::MixedModels.GeneralizedLinearMixedModel{Float64}) at /Users/mm51929/.julia/v0.6/MixedModels/src/PIRLS.jl:195
```

I'm using (from Pkg.status()):
```
- NLopt                         0.3.6              master
- MixedModels                   0.12.0+            master
```

I've managed to whittle down to this minimal example of it happening:

```
glmm_fit = fit!(glmm(@formula(sale_label ~ 1 + a + (1 | cluster)), df, Binomial(), LogitLink()))
```

```
julia> describe(df[[:sale_label,:a,:cluster]])
sale_label
Summary Stats:
Mean:           0.080000
Minimum:        0.000000
1st Quartile:   0.000000
Median:         0.000000
3rd Quartile:   0.000000
Maximum:        1.000000
Length:         100
Type:           Int64
Number Missing: 0
% Missing:      0.000000

a
Summary Stats:
Mean:           0.114521
Minimum:        -1.059035
1st Quartile:   -0.617305
Median:         -0.255889
3rd Quartile:   0.543240
Maximum:        6.843916
Length:         100
Type:           Float64
Number Missing: 0
% Missing:      0.000000

cluster
Summary Stats:
Mean:           14.980000
Minimum:        1.000000
1st Quartile:   4.000000
Median:         20.000000
3rd Quartile:   20.000000
Maximum:        20.000000
Length:         100
Type:           Int64
Number Missing: 0
% Missing:      0.000000
```

Any suggestions?

**Comment by andyreagan** [comment]
Here is a dataframe that I was using, very simple:

[sample_dataframe.csv.gz](https://github.com/dmbates/MixedModels.jl/files/1480526/sample_dataframe.csv.gz)

**Comment by hikea** [comment]
I think it is a problem with your data. Using `fast=true` might help, but look at this two issues --> https://github.com/dmbates/MixedModels.jl/issues/98 and https://github.com/dmbates/MixedModels.jl/issues/94

**Comment by andyreagan** [comment]
Okay thanks- I searched the issues for NLOpt, but didn't come up with anything.

**Comment by dmbates** [comment]
@hikea is right.  For a GLMM the optimization to determine the parameter estimates is done in two stages.  The `fast` optimization gets very close to the optimum quickly.  The estimates from this phase are used as the starting values for the second phase.  This all works nicely except when the first phase converges on the boundary.  That is, the estimated standard deviation of some scalar random effects is zero or the estimated covariance matrix of some vector-valued random effects is singular.  In that case NLopt complains about the starting estimates in the second phase.

I guess I should trap that case and throw a warning.

**Comment by dmbates** [comment]
The two stages of the optimization are described in

http://dmbates.github.io/MixedModels.jl/stable/optimization.html#Generalized-Linear-Mixed-Effects-Models-1

**Comment by andyreagan** [comment]
Awesome. Let me see if I can write the code to catch that.

**Comment by dmbates** [comment]
@andyreagan Thanks for the offer.  The place to check is the block
```jl
    if !fast
        fit!(m, verbose=verbose, fast=true)
        optsum.lowerbd = vcat(fill!(similar(β), T(-Inf)), optsum.lowerbd)
        optsum.initial = vcat(β, m.θ)
        optsum.final = copy(optsum.initial)
        optsum.initial_step = vcat(stderr(m) ./ 3, min.(T(0.05), m.θ ./ 4))
    end
```
in the `fit!` method for `GeneralizedLinearMixedModel`.  Before modifying `optsum.lowerbd` check for zeros in any positions of `m.θ` for which `optsum.lowerbd` is zero.  If the converged estimates in those positions were very small positive values they should have been replaced by zeros in the blocks with `xmin_` a bit further down, but I would check anyway.

**Comment by andyreagan** [comment]
Closing this in favor of #95 (redundant)
