### ISSUE TITLE
Respect user-defined ordering of Categorical variables

### ISSUE THREAD

**Issue by andyreagan** [dmbates/MixedModels.jl#114]
The internals of the package rely on the `.refs` of the CategoricalArray type.
While I don't fully understand how the CategoricalArray type is _intended_ to be used, the refs seem to be internal, whereas the `order` can be changed by a user.
> This may result in surprising labels for the results of `ranef` when `named = true.`

@nalimilan understands this and can perhaps better explain how to use CategoricalArray (where the documentation is thin).
AFAIK, there are stored `levels` and a stored `order` for those levels. Levels don't have to be ordered, but they can be (the ordered state is stored on the Array). The order itself is an array that maps from the refs to the static levels (stored as an array, regardless of whether they can be ordered). Levels can contain more values than are available in the data (though not less).

I'll copy in a couple notes from a previous discussion:
> CategoricalArrays.order(a.pool)[a.refs[i]] will give you the position of the entry i in levels. The refs only give you the position in the index, which does not reflect the user-defined ordering.

**Comment by nalimilan** [comment]
Categorical arrays are always ordered (somewhat). The `ordered!` function just determines whether the values can be compared using `<`, but for this package that shouldn't make a difference.

**Comment by andyreagan** [comment]
Right, so by "respect user-definied ordering", what I mean is `levels`.

**Comment by andyreagan** [comment]
So, for a user to be able to set ordering (i.e., by setting `levels!`), this package needs to use the `order` lookup rather than `refs` directly.

**Comment by andyreagan** [comment]
Yes: the "ordered" property of a CategoricalArray, accessed by `isorderd()`, etc, is not relevant for our discussion here. It is meant to encode an ordinal variable as opposed to a nominal one, and does not have any bearing on the `levels` of the array.

Herein, when I refer to the "order", I mean the specific order of elements in `levels`.

I did some testing, and here's what I found:

- The `.refs` reflects the order in which elements are seen in the CategoricalArray upon construction.
    - This means that they are very specific to the DataFrame seen (and sensitive to DataFrame construction).
- The `levels` of an array are sorted when it is constructed (in this way, it is not the same as `unique` of the original array).
- `.refs` are not an index for levels (we knew this, and of course it is clear given the above two), you have to through the `CategoricalArrays.order()` to get the original levels back. Again, this is fundamentally because the `levels` are not restricted to be ordered by the appearance in the data, whereas the `refs` are that way.
- `.refs` do not respect missing levels. If there are more levels specified than seen in the data, (either in the middle or at the ends), there is no ref for them (of course, but nor is there a gap in the refs indices either).
    - Potential issue: moving this package towards respecting user-defined levels could create zero columns in the design matrices.

There are two advantages (goals) and one potential issue that I see for not using `refs` directly. Advantages:

- The `refs` depend upon the order of elements when the arrays are constructed, and in turn the specialized arrays created within MixedModels for random effects have the same dependency. This means that the `levels` corresponding to each random effect group are inconsistent with the ordering of the `levels` on the arrays. Specifically, `ranef(m)` will not be as expected here:
https://github.com/dmbates/MixedModels.jl/blob/9d70f8f516599a6174638d5bd4a009716c77167e/src/modelterms.jl#L225
- By respecting the user's set `levels`, this will enable use of methods that rely on upon the internals of MixedModels objects ordering but do not have data with the same `ref` structure (including, but not limited to the aforementioned `ranef`).

Potential issue:

- There may be empty columns when a user specifies more levels than are in the data, and the model may not be able to be fit (we will have rank deficiency). This control of levels, given to the user of the package, would allow them to fix the issue, but it should at least given a warning (if `length(unqiue(a)) != length(levels(a))`).

**Comment by Nosferican** [comment]
Best solution would be to accept the contrasts for StatsModels.ModelFrame.

**Comment by nalimilan** [comment]
I hadn't noticed @andyreagan's comment, but I totally agree that one should use `levels`. The ordering used by the `refs` field should be an implementation detail invisible to users. But AFAIK that's what the package currently does, after to @dmbates's recent PRs.

**Comment by nalimilan** [comment]
Yes.

**Comment by dmbates** [comment]
@andyreagan Have you checked with recent versions of this package?  I think this should be resolved but I would appreciate it if you could check before I close the issue.

**Comment by andyreagan** [comment]
@dmbates thanks for reaching out. I'll take a look this afternoon!

**Comment by andyreagan** [comment]
@nalimilan @dmbates looks okay to me! I had written a `predict` function that was safe the previous issues with refs, and it would be much easier to do with these fixes.

https://github.com/andyreagan/MixedModels.jl/blob/predict-new/src/pls.jl#L232
https://github.com/andyreagan/MixedModels.jl/blob/predict-new/src/PIRLS.jl#L97

with some tests here:

https://github.com/andyreagan/MixedModels.jl/blob/predict-new/test/pls.jl#L25
https://github.com/andyreagan/MixedModels.jl/blob/predict-new/test/pirls.jl#L53

(and the predict function exported with the module).
