### ISSUE TITLE
Undefined method with MixedModels 0.13 on Julia 0.6.2

### ISSUE THREAD

**Issue by protogeezer** [dmbates/MixedModels.jl#115]
I can't seem to find a version of MixedModels that works on 0.6.2. Pkg won't install a version after 0.13.
Any guidance about how to get everything consistent would be great. So, what I'm seeing is:

julia> using RData, DataFrames, MixedModels
INFO: Recompiling stale cache file /Users/sjbespa/.julia/lib/v0.6/MixedModels.ji for module MixedModels.
WARNING: Method definition model_response(DataFrames.ModelFrame) in module DataFrames at /Users/sjbespa/.julia/v0.6/DataFrames/src/statsmodels/formula.jl:352 overwritten in module MixedModels at /Users/sjbespa/.julia/v0.6/MixedModels/src/pls.jl:61.

Then when I fit a model:
fm = fit!(lmm(@formula(score ~ 1 + year + (1 + year | S7_ID) + (1 + year | CHILDID)), j1))
WARNING: both StatsBase and DataFrames export "coefnames"; uses of it in module MixedModels must be qualified
ERROR: UndefVarError: coefnames not defined
Stacktrace:
 [1] #lmm#16(::Array{Any,1}, ::Dict{Any,Any}, ::Distributions.Normal{Float64}, ::Function, ::DataFrames.Formula, ::DataFrames.DataFrame) at /Users/sjbespa/.julia/v0.6/MixedModels/src/pls.jl:112
 [2] lmm(::DataFrames.Formula, ::DataFrames.DataFrame) at /Users/sjbespa/.julia/v0.6/MixedModels/src/pls.jl:83

Finally, if I try doing a checkout of master:
julia> Pkg.checkout("MixedModels")
INFO: Checking out MixedModels master...
INFO: Pulling MixedModels latest master...
ERROR: resolve is unable to satisfy package requirements.
  The problem was detected when trying to find a feasible version
  for package Showoff.
  However, this only means that package Showoff is involved in an
  unsatisfiable or difficult dependency relation, and the root of
  the problem may be elsewhere.

**Comment by nalimilan** [comment]
You probably have a version mismatch in the dependencies of MixedModels. Check that you are using the latest versions of DataFrames, StatsBase and StatsModels (use `Pkg.status` to get this information).

**Comment by protogeezer** [comment]
I definitely do not have the latest versions of most packages for some reason.

I tried (with no joy) to delete the entire directory ~/.julia/v0.6 and reloaded all the packages. Including 

Pkg.add(“MixedModels”)

How do I get the latest versions?

**Comment by nalimilan** [comment]
That's probably because you have installed packages which require DataFrames < 0.11. Unless you can remove these packages, stay with the latest version of MixedModels which is compatible with DataFrames 0.10.1.

**Comment by protogeezer** [comment]
It appears that Gadfly and RData are the culprits - I'll file issues with those packages. Thanks.

**Comment by dmbates** [comment]
@protogeezer It comes down to which packages allow for `DataFrames` v0.11.1 or later (v0.11.3 is the current release) and which cap the version of `DataFrames` at 0.11.0.  The current dependencies of `Gadfly` end up conflicting with v0.11.1 or later of DataFrames, although I don't see from a brief glance how this happens.  You can try installing the latest DataFrames, CategoricalArrays, etc. then installing `Gadfly` and you will find that it downdates many packages.

I'm pretty sure the Gadfly developers are aware of the problem.  It's just that it has a lot of dependencies.

**Comment by protogeezer** [comment]
Thanks. 

The dependency that is in the Gadfly REQUIRE file is something like DataFrames 0.4 - which actually might be a DataArray dependency. When I tried checking out the master it griped about not being able to find a reasonable version of ShowOff, of all things. On a whim, I changed the dependency to 0.10.0 and everything updated. That’s good enough for me at this point.

Stephen

**Comment by nalimilan** [comment]
The problem with RData is known, it's waiting for changes in CSV.jl. Not sure about Gadfly, but I think it's related to RData.
