### ISSUE TITLE
Crash in ranef with MixedModels 0.16

### ISSUE THREAD

**Issue by protogeezer** [dmbates/MixedModels.jl#116]
running a simple VAM:
fm = fit!(lmm(@formula(score ~ 1 + year + (1 + year | S7_ID) + (1 + year | CHILDID)), j1))
followed by
ranef(fm)
results in:
ERROR: MethodError: no method matching αβAc_mul_B!(::Float64, ::MixedModels.BlockedSparse{Float64,Int32}, ::Array{Float64,1}, ::Float64, ::Array{Float64,1})
Closest candidates are:
...
Stacktrace:
 [1] ranef!(::Array{Array{Float64,2},1}, ::MixedModels.LinearMixedModel{Float64}, ::Array{Float64,1}, ::Bool) at /Users/sjbespa/.julia/v0.6/MixedModels/src/mixedmodel.jl:126
 [2] #ranef#65(::Bool, ::Bool, ::Function, ::MixedModels.LinearMixedModel{Float64}) at /Users/sjbespa/.julia/v0.6/MixedModels/src/mixedmodel.jl:152
 [3] ranef(::MixedModels.LinearMixedModel{Float64}) at /Users/sjbespa/.julia/v0.6/MixedModels/src/mixedmodel.jl:149

A fix that seems to have gotten me going so I can finish my presentation slides  is:
diff -u  ~/MixedModels.jl-master/src/linalg.jl linalg.jl
--- /Users/sjbespa/MixedModels.jl-master/src/linalg.jl	2017-12-11 11:43:04.000000000 -0700
+++ linalg.jl	2018-01-02 12:08:07.000000000 -0700
@@ -53,6 +53,9 @@
 
 αβAc_mul_B!(α::T, A::SparseMatrixCSC{T}, B::StridedVector{T}, β::T,
             C::StridedVector{T}) where T = Ac_mul_B!(α, A, B, β, C)
+            
+αβAc_mul_B!(α::T, A::BlockedSparse{T}, B::StridedVector{T}, β::T,
+            C::StridedVector{T}) where T = Ac_mul_B!(α, A.cscmat, B, β, C)
 
 function Ac_ldiv_B!(A::LowerTriangular{T,UniformBlockDiagonal{T}}, B::StridedVector{T}) where {T}
     @argcheck length(B) == size(A, 2) DimensionMismatch

**Comment by dmbates** [comment]
Thanks for the report and for the fix.

Can you describe the configuration of `S7_ID` and `CHILDID`?  Is `CHILDID` nested within `S7_ID`?  If you could provide an example it would help in writing tests but I can understand if your data are proprietary and you can't do so.

**Comment by protogeezer** [comment]
Yes childid is nested in s7_id (child’s school during 7th wave of the (public) ECLS-98 database. I can’t find the data for using your drop box - so can I just email you the data frame I used (j1 in the issue)?

**Comment by dmbates** [comment]
Yes, please.  Just email it.  As it is public, can I incorporate it in the `dat.rda` file in the `test` directory?

**Comment by protogeezer** [comment]
OK I’ll send the two files (test file and data sample) to your university email. Github strips attachments.

We should discuss what data from the ECLS-98 and ECLS-11 to add to your library (those data bases have something like 15K students and 15K variables.) The small sample attached is nearly worthless for anything but testing the code?

With appropriate file paths:

using CSV, MixedModels, StatsModels
include("re_test.jl")
j1 = CSV.read("/Users/sjbespa/Desktop/testscores.csv")
form = @formula(score ~ 1 + year + (1 + year | S7_ID) + (1 + year | CHILDID))
re_hypothesis_test(form,j1)

Stephen

PS - the code is the beginnings of a hypothesis test for the presence of random effects in the data frame. (Demidenko shows in the proof/derivation that the test is more general than (or includes) all the special cases in other books that he cites). See Demidenko’s book section 3.5. If you’d like to have that in the MixedModel quiver, please explain how such a thing would integrate into the MixedModel structure. I’ll finish it when I get back from my business trip.
