### ISSUE TITLE
unable to update to new version

### ISSUE THREAD

**Issue by IgorDouven** [dmbates/MixedModels.jl#121]
I'm trying to update to the latest version, but when I use `Pkg.update("MixedModles")`, the message I receive is this:

Package MixedModels was set to version 0.13.0, but a higher version 0.16.3 exists. To install the latest version, you could try doing a full update with `Pkg.update()`.

Then when I run `Pkg.update()`, I get the message that there are no packages to install. Finally, when I run `Pkg.clone("https://github.com/dmbates/MixedModels.jl")`, I receive the message that MixedModels already exists.

I'm currently using the latest version of JuliaPro, which I downloaded two days ago, but I had the issue before (but was hoping it would get resolved by the update).

What am I doing wrong?

**Comment by nalimilan** [comment]
That's probably due to DataFrames, see https://discourse.julialang.org/t/how-to-upgrade-from-dataframes-0-10-1-to-0-11-3/8243/.

**Comment by IgorDouven** [comment]
That doesn't seem to be the problem in my case. `Pkg.installed("DataFrames")` returns 0.11.5+. In fact, when I now run `Pkg.update("MixedModels")` I get the warning that DataFrames is fixed at 0.11.5+ conflicting with requirement for MixedModels: [0.9.0, 0.11.0). Julia then recommends that I use `Pkg.free("MixedModels")` to update to version 0.16.3 of MixedModels, but when I do that, I get an error message: MixedModels cannot be freed -- repo is dirty.

**Comment by nalimilan** [comment]
OK, so that's because some files have been modified in the MixedModels directory. If you don't care about them, just remove that directory (or move it elsewhere).

**Comment by IgorDouven** [comment]
I tried to remove the package, then to reinstall, but that didn't work. I suppose I'd have the remove the directory via the terminal then, but I didn't manage to do that. I think I'll just wait until all these package inconsistencies are resolved.

**Comment by nalimilan** [comment]
Yes, you need to remove the directory manually, but you can do that with your file manager. Note that the problem won't resolve on its own as it's due to a problem on your local system.

**Comment by IgorDouven** [comment]
It worked -- many thanks!
