### ISSUE TITLE
MixedModels not working in Julia 0.7 

### ISSUE THREAD

**Issue by harishharman** [dmbates/MixedModels.jl#129]
I have downloaded the 0.7 Julia and installed MixedModels package (ubuntu 17.2). During the usage i got below error. I also tried Pkg.resolve.

julia> using MixedModels
[ Info: Precompiling module MixedModels
ERROR: LoadError: ArgumentError: Package MixedModels does not have Compat in its dependencies:

If you have MixedModels checked out for development and have
added Compat as a dependency but haven't updated your primary
environment's manifest file, try Pkg.resolve().
Otherwise you may need to report an issue with MixedModels.
Stacktrace:
[1] require(::Module, ::Symbol) at ./loading.jl:862
[2] include at ./boot.jl:317 [inlined]
[3] include_relative(::Module, ::String) at ./loading.jl:1075
[4] include(::Module, ::String) at ./sysimg.jl:29
[5] top-level scope at none:0
[6] eval at ./boot.jl:319 [inlined]
[7] eval(::Expr) at ./client.jl:394
[8] top-level scope at ./none:3 [inlined]
[9] top-level scope at ./:0
in expression starting at /home/usr/.julia/packages/MixedModels/aNHq/src/MixedModels.jl:5
ERROR: Failed to precompile MixedModels to /home/usr/.julia/compiled/v0.7/MixedModels/tBiY.ji.
Stacktrace:
[1] error at ./error.jl:33 [inlined]
[2] compilecache(::Base.PkgId) at ./loading.jl:1205
[3] _require(::Base.PkgId) at ./loading.jl:1007
[4] require(::Base.PkgId) at ./loading.jl:879
[5] require(::Module, ::Symbol) at ./loading.jl:874

**Comment by dmbates** [comment]
Thanks for catching that.  I have added `Compat` to the `REQUIRE` file on the `master` branch and will release a new version later today.

Unfortunately, that is just one of many impediments to having this package run on v0.7.  Many other packages in its dependencies must be updated for v0.7 before this package can be.  There is an ongoing effort to upgrade these more basic building blocks.

**Comment by dmbates** [comment]
I have just created version 0.18.1.  It should be added to the registry tomorrow.

This doesn't mean that the package will be usable with julia `v0.7.0-beta`.  Several dependencies such as `NLopt`, `GLM` and `Distributions` need to be updated first.

**Comment by harishharman** [comment]
@dmbates Thanks for the update.  I am not going to retest until all the dependencies are updated.  Do i need to close this issue or keep it open?

**Comment by dmbates** [comment]
Let's keep the issue open.  That way there will be a definite sign when the package and its dependencies have been updated to run on v0.7.0

**Comment by dmbates** [comment]
Update submitted as https://github.com/JuliaLang/METADATA.jl/pull/17947
