### ISSUE TITLE
Random estimates Named array messed up (Julia 0.6.3)?

### ISSUE THREAD

**Issue by harishharman** [dmbates/MixedModels.jl#130]
Please check the named array output of the Random effects. It looks like jumbled up or not assigning coeffs to the right column header.
randomDF = ranef(mm1, named=true)[1]

We are working on the sample data set to prove it. If you can check this issue without sample please go  ahead else we will get back to you with samples input and outputs (2-3 days).

**Comment by dmbates** [comment]
It appears that I missed some of the subtlety in how the levels are defined in [`CategoricalArrays`](https://github.com/nalimilan/CategoricalArrays.jl.git).

**Comment by dmbates** [comment]
I think I have a fix but I don't have a reproducible example.  Would you be willing to try after
```
Pkg.checkout("MixedModels")
```
to see if this works for you?

**Comment by harishharman** [comment]
julia> Pkg.checkout("MixedModels")
INFO: Checking out MixedModels master...
INFO: Pulling MixedModels latest master...
INFO: No packages to install, update or remove

is this right?

**Comment by dmbates** [comment]
Now do the test on fitting the model and checking the random effects order.

**Comment by harishharman** [comment]
If you look at the last INFO. It looks like update was  not successful. 
INFO: No packages to install, update or remove

Even though i tried my data and same issue no change

**Comment by dmbates** [comment]
I forgot to push my changes to github. Now done.  Please try again.

**Comment by harishharman** [comment]
@dmbates  Just did one round of test and looks good. I will do one more round of test tomorrow and clsoe this issue. Thank you.
