### ISSUE TITLE
Mixed Model with 3 nested grouping factors, random intercepts, and random slopes

### ISSUE THREAD

**Issue by jen265** [dmbates/MixedModels.jl#131]
I'm trying to fit a mixed model with 3 nested grouping factors (cities nested in states nested in countries), random intercepts, and random slopes (random intercepts and random slopes are uncorrelated) as in the following model:

mod = @formula(Y ~ 1 + attitude * city_attitude + attitude * state_attitude + attitude * country_attitude 
+ (1 | city) + ((0 + attitude) | city)
+ (1 | state) + ((0 + attitude) | state) + ((0 + city_attitude) | state)
+ (1 | country) + ((0 + attitude)| country) + ((0 + city_attitude) | country) + ((0 + state_attitude) | country))

This model results in the following Method Error:
MethodError: no method matching αβA_mul_Bc!(::Float64, ::MixedModels.BlockedSparse{Float64,Int32}, ::MixedModels.BlockedSparse{Float64,Int32}, ::Float64, ::MixedModels.BlockedSparse{Float64,Int32})

When I include only 2 of the 3 grouping factors, the model fits without errors. Is it possible to fit a model with 3 nested grouping factors as above?

**Comment by dmbates** [comment]
@jen265 Sorry to take so long to respond to this question.  I have been working on updating this packages and some of the packages on which it depends to run with Julia v1.0.0.

Could you please update your version of the package to MixedModels v1.1.0 (one way is
```julia
using Pkg; Pkg.update()
```
and check if this is still a problem for you.  If so, could you provide me with a sample data set?  These kinds of issues depend strongly on the configuration of the factors like `city`, `state` and `county` and it is difficult to decide exactly what configuration is going to generate the issue.

It looks as if these three factors are nested - `city` within `county` within `state`.  Is that the case?

**Comment by jen265** [comment]
@dmbates Thank you very much for your reply. I installed Julia v1.1.0 and MixedModels v1.1.0 and tried it again. Unfortunately, the model still results in the following Method Error:
MethodError: no method matching αβA_mul_Bc!(::Float64, :: BlockedSparse{Float64,Int32}, ::BlockedSparse{Float64,Int32}, ::Float64, :: BlockedSparse{Float64,Int32})

When I include only 2 of the 3 grouping factors, the model fits without errors. In the model, city is nested within state, which in turn is nested in country. The values of city indicate the city as well as the state and country in which the city is located; the values of state indicate the state as well as the country in which the state is located. I will send you a sample data set.
