### ISSUE TITLE
Release for Julia 1.0

### ISSUE THREAD

**Issue by Nosferican** [dmbates/MixedModels.jl#132]
Leaving this issue to track progress.

**Comment by Nosferican** [comment]
@dmbates, I will be developing some packages that will use MixedModels.jl as dependency and wanted to check on the plans/timeline to update this package or if there was anything to speed the process. I believe the only dependency missing a 1.0 compat release is GLM, but it has a PR that is 1.0 compatible; if not this [fork](https://github.com/Nosferican/GLM.jl) is.

**Comment by Nosferican** [comment]
@dmbates Let me know if there is anything I can do to help out or a time estimate. Thanks!

**Comment by dmbates** [comment]
I am currently working on the `0.7updates` branch.  The change from generics like `Ac_mul_B!` to various versions of `mul!` will require substantial code modifications.  I am still trying to get femtocleaner working but haven't yet succeeded.  If you know what is required to trigger a femtocleaner run I would appreciate any hints.

**Comment by Nosferican** [comment]
In my experience FemToCleaner even in the 1% times that actually works is not nearly as helpful as last time (0.5 -> 0.6). Deprecations.jl was never updated thoroughly this cycle. I finished updating GLM and QuantEcon so I can probably help out a bit with a few of the deprecations. I am developing a package which will wrap MixedModels so I can totally help out getting it sooner than later.

**Comment by Nosferican** [comment]
I am having an issue identifying where `UniformBlockDiagonal` is defined.

**Comment by dmbates** [comment]
I have reached an impasse at commit https://github.com/dmbates/MixedModels.jl/commit/d169823ad265e10e99d5b9744353f91fd25c17e2 in the 0.7updates branch.  A simple model fit, such as `fm1` in `test/pls.jl` fails on a method error when trying to construct the `LinearMixedModel` object. 
```julia
julia> using DataFrames, LinearAlgebra, MixedModels, SparseArrays, RData, StatsBase, Test

julia> const dat = Dict(Symbol(k) => v for (k,v) in load("/home/bates/.julia/dev/MixedModels/test/dat.rda"));

julia> fm1 = LinearMixedModel(@formula(Y ~ 1 + (1|G)), dat[:Dyestuff])
ERROR: MethodError: no method matching *(::Adjoint{Float64,MatrixTerm{Float64,Array{Float64,2}}}, ::ScalarFactorReTerm{Float64,UInt8})
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:502
  *(::Adjoint{T,MatrixTerm{T,S} where S<:(AbstractArray{T,2} where T)}, ::AbstractFactorReTerm{T}) where T at /home/bates/.julia/dev/MixedModels/src/modelterms.jl:385
  *(::Adjoint{T,ScalarFactorReTerm{T,R}}, ::ScalarFactorReTerm{T,S}) where {T, R, S} at /home/bates/.julia/dev/MixedModels/src/modelterms.jl:428
  ...
Stacktrace:
 [1] LinearMixedModel(::StatsModels.Formula, ::Array{MixedModels.AbstractTerm{Float64},1}, ::Array{Float64,1}) at /home/bates/.julia/dev/MixedModels/src/pls.jl:37
 [2] #LinearMixedModel#16(::Array{Any,1}, ::Dict{Any,Any}, ::Distributions.Normal{Float64}, ::Type, ::StatsModels.Formula, ::DataFrame) at /home/bates/.julia/dev/MixedModels/src/pls.jl:106
 [3] LinearMixedModel(::StatsModels.Formula, ::DataFrame) at /home/bates/.julia/dev/MixedModels/src/pls.jl:63
 [4] top-level scope at none:0
```
 I can't understand why the second method in the "closest candidates" doesn't apply.  I have been at this all day and I am tired enough that I may be missing something obvious.  Can you see anything?

**Comment by dmbates** [comment]
UniformBlockDiagonal is defined in src/types.jl

**Comment by dmbates** [comment]
Yes. I have made several commits to this branch. It is still not passing the tests but I hope to get there today.

**Comment by dmbates** [comment]
@Nosferican Can you check the current master on version 0.7 or, if you use https://github.com/JuliaStats/StatsModels.jl/tree/0.7patch, version 1.0

**Comment by Nosferican** [comment]
Sure, should I checkout the StatsModels branch as well?

**Comment by dmbates** [comment]
The main difference between 0.7 and 1.0 is that deprecation warnings in 0.7 are changed into errors in 1.0.  The simplest approach is to use 0.7.  The alternative is to checkout the `0.7patch` branch of `StatsModels` and use 1.0.  Whichever seems most reasonable to you.

**Comment by dmbates** [comment]
I expect that there will soon be a new release of `StatsModels` with the simple change to allow it to support `MixedModels` on 1.0

**Comment by Nosferican** [comment]
The tests seem to pass all clear, just one deprecation which showed up (missing a `dims`)
```
Warning: `sum(a::AbstractArray, dims)` is deprecated, use `sum(a, dims=dims)` instead.
│   caller = droprandomeffects(::StatsModels.Terms) at modelmatrix.jl:102
```
Shouldn't fixing the remaining deprecation make it 1.0 test passing?

**Comment by Nosferican** [comment]
Here to track the patch, JuliaLang/METADATA.jl#17935.

**Comment by dmbates** [comment]
I have updated the `REQUIRE` file (and the docs) now that `StatsModels v0.3.1` is in place.  Just waiting for the CI checks to run.

**Comment by dmbates** [comment]
Package submitted as https://github.com/JuliaLang/METADATA.jl/pull/17947
