### ISSUE TITLE
Extract data used for fitting

### ISSUE THREAD

**Issue by DominiqueMakowski** [dmbates/MixedModels.jl#135]
Dear @dmbates, I am trying to access the data (passed as a DataFrame) used for fitting the model, but can't find it in the internals of an `lmm`. Is it possible, and how, to access this data?

For instance, in GLMs the data is stored in `model.mf.df`.

Thanks a lot!

**Comment by dmbates** [comment]
Sorry for the delay in responding.  I have been traveling and, as always seems to happen, creating talks at the last minute even though I had 6 months lead time.

The original model frame (which is what `mf` is in a `LinearModel` or `GeneralizedLinearModel`) is not stored in the `LinearMixedModel` and `GeneralizedLinearMixedModel` objects.  The model matrices are embedded in the components of the `trms` field.

Is there a reason that you would need it?

**Comment by DominiqueMakowski** [comment]
Closing this (discussed in #136)
