### ISSUE TITLE
Standardized coefs

### ISSUE THREAD

**Issue by DominiqueMakowski** [dmbates/MixedModels.jl#136]
This is a follow up for #135 about what I would require the dataframe used for fitting.

Mixed models are (although too slowly) becoming the default and one of the most widely used methods in psychology. However, there are certain limitations for users and reviewers that in my opinion slow the transition. In particular, users often are not sure about how and what to report in their manuscript (based on the output provided for instance by R), leading to a high variability in the reported information (with often missing or unexact stuff). Moreover, we are often required (by reviewers/supervisors) to provide additional metrics, which can be statistically not relevant or debatable or useless or wrong for mixed models (cf the long debate around p values, pseudo-R² and so on).  

In this context, I am trying to create small convenience functions to ease data analysis in the psychology field, that takes a result (for example a mixed model) and returns a formatted textual output, with the goal of standardizing the reports (with, by default, the inclusion of "best practices").

I started implementing this for GLMs (see [here](https://github.com/neuropsychology/Psycho.jl#linear-models-lm), it's in very WIP state) and would like to do it for GLMMs. One of the ingredients I'd like to include is the possibility of returning standardized coefficients, to allow their categorization as index of "effect size" with a set of rules of thumb (such as Cohen's 1988 or their own).

Long story short, I've seen that one method of computing such std coefs is basically to directly transform the coefficient (and divide it by the SD of the outcome variable). However, I believe that this method provides misleading values in some cases (such as interaction effects). The other method is to standardize the data beforehand, refit the model and extract the coefs of this model. The main limitation is that it is computationally costly (as one have to fit the model two times), but in most use-cases in psychology, frequentist models are quite fast to compute, so this additional time is acceptable. 

This is why I would need the original dataframe, to be able to standardize it and update (re-fit) the model to get "standardized coefs". Is there any other way of computing them using model matrices? Thank you

**Comment by DominiqueMakowski** [comment]
@nalimilan How would it work?

**Comment by dmbates** [comment]
I was going to mention that if you just need the model matrix for the fixed-effects terms that is stored, as a plain matrix in transposed form, as part of the second last component of the `trms` field.  I could quite easily add an extractor for that.

**Comment by nalimilan** [comment]
> @nalimilan How would it work?

I don't know precisely, but that's clearly an issue which is going to be raised with lots of other model families, so we need a general solution. Better discuss that in a StatsModels issue.

**Comment by dmbates** [comment]
If it will help I have just committed changes to the "getproperty" branch so that you can retrieve the fixed-effects model matrix as
```julia
julia> m.X
30×1 Array{Float64,2}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0
```
and the response vector as
```julia
julia> show(m.y)
[1545.0, 1440.0, 1440.0, 1520.0, 1580.0, 1540.0, 1555.0, 1490.0, 1560.0, 1495.0, 1595.0, 1550.0, 1605.0, 1510.0, 1560.0, 1445.0, 1440.0, 1595.0, 1465.0, 1545.0, 1595.0, 1630.0, 1515.0, 1635.0, 1625.0, 1520.0, 1455.0, 1450.0, 1480.0, 1445.0]
```

**Comment by DominiqueMakowski** [comment]
I'll close this issue for now in the hope that a more general solution will be found (see [here](https://github.com/JuliaStats/StatsModels.jl/issues/75)). Thanks a lot for your help!
