### ISSUE TITLE
How can I use MixedModels.jl without random effects?

### ISSUE THREAD

**Issue by skanskan** [dmbates/MixedModels.jl#147]
When I try it says I can't, I need random-effects.
I'd like to use the same package for fixed effects.
And if I try to create a fake variable with non-repeating values it also complains.
Regards.

**Comment by Nosferican** [comment]
If you don't need random effects, could you just use GLM?

**Comment by Nosferican** [comment]
MixedModels uses GLM as a dependency so there isn't any extra dependencies or such. If you want yu could just make a function that calls `LinearMixedModel` if it has random effects and `LinearModel` if it doesn't. As a wrapper you can just use that one.

**Comment by dmbates** [comment]
I agree with @Nosferican .  This package is advertised for fitting mixed-effects models and, by definition, that means models that have both fixed-effects parameters and random effects.
