### ISSUE TITLE
MixedModels, no method matching rankUpdate!

### ISSUE THREAD

**Issue by marynavickt** [dmbates/MixedModels.jl#152]
I get an error 

no method matching rankUpdate!(::Hermitian{Float64,Array{Float64,2}}, ::BlockedSparse{Float64,Int32}, ::Float64)
Closest candidates are:
  rankUpdate!(::Union{Hermitian{T<:Union{Float32, Float64},S<:(Union{DenseArray{T,2}, ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, AbstractCartesianIndex},N} where N} w

when try to fit the model with a formula like this
Y ~ X1 + X2+ X3 +   X4 + (X5 + X6 +   X7 + X8 |R1) +  (X9 + X10 + X11 + X12|R2) + 
   (X13| R3) + (X14| R4) +  (1+X15| R5)

The problem disappear when I remove the expression "(X5 + X6 +   X7 + X8 |R1)"  or simply move R1 to different places in formula.

**Comment by dmbates** [comment]
It's interesting that the error depends on the order of the random-effects terms.

Could you make your data available for me to try it out?  If that is not possible, could you show us the output of `describeblocks` applied to your model?

These errors come about when the structure of the random-effects terms creates different types of matrices in the blocked Cholesky factor.  Part of the factorization process updates the diagonal blocks after blocks to the left of them have been determined.  In this case it looks like the diagonal block is dense but I don't see what type the block on the left is.

**Comment by marynavickt** [comment]
Sorry, can't share data, it's all confidential.
Output of describeblocks:

1,1: UniformBlockDiagonal{Float64} (1888, 1888) UniformBlockDiagonal{Float64}
2,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (340, 1888) BlockedSparse{Float64,Int32}
2,2: UniformBlockDiagonal{Float64} (340, 340) UniformBlockDiagonal{Float64}
3,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (128, 1888) BlockedSparse{Float64,Int32}
3,2: Array{Float64,2} (128, 340) Array{Float64,2}
3,3: UniformBlockDiagonal{Float64} (128, 128) Array{Float64,2}
4,1: SparseArrays.SparseMatrixCSC{Float64,Int32} (12, 1888) BlockedSparse{Float64,Int32}
4,2: SparseArrays.SparseMatrixCSC{Float64,Int32} (12, 340) BlockedSparse{Float64,Int32}
4,3: Array{Float64,2} (12, 128) Array{Float64,2}
4,4: UniformBlockDiagonal{Float64} (12, 12) Array{Float64,2}
5,1: Array{Float64,2} (4, 1888) Array{Float64,2}
5,2: Array{Float64,2} (4, 340) Array{Float64,2}
5,3: Array{Float64,2} (4, 128) Array{Float64,2}
5,4: Array{Float64,2} (4, 12) Array{Float64,2}
5,5: UniformBlockDiagonal{Float64} (4, 4) Array{Float64,2}
6,1: Array{Float64,2} (5, 1888) Array{Float64,2}
6,2: Array{Float64,2} (5, 340) Array{Float64,2}
6,3: Array{Float64,2} (5, 128) Array{Float64,2}
6,4: Array{Float64,2} (5, 12) Array{Float64,2}
6,5: Array{Float64,2} (5, 4) Array{Float64,2}
6,6: Array{Float64,2} (5, 5) Array{Float64,2}
7,1: Array{Float64,2} (1, 1888) Array{Float64,2}
7,2: Array{Float64,2} (1, 340) Array{Float64,2}
7,3: Array{Float64,2} (1, 128) Array{Float64,2}
7,4: Array{Float64,2} (1, 12) Array{Float64,2}
7,5: Array{Float64,2} (1, 4) Array{Float64,2}
7,6: Array{Float64,2} (1, 5) Array{Float64,2}
7,7: Array{Float64,2} (1, 1) Array{Float64,2}
NULL

**Comment by dmbates** [comment]
Are any of the covariates `X1, X2, ..., X15` categorical or are they all numeric?  I am trying to understand the dimensions of the random effects for `R1` in particular.  My best guess is that the 1888 comes from 8-dimensional random effects for each of 236 levels of `R1`.  Is that the case?
Perhaps the easiest approach is if you could just tell me how many levels there are in each of `R1, ..., R5`.

By the way, it looks as if the grouping factor `R5` only has two levels present in the data.  It is not a good idea to incorporate it as a random effect.  You are trying to estimate two variances and a covariance from information on only two groups.

Also, are there duplicates in the covariates `X1, X2, ..., X15`.  The way the model is defined a covariate in a random effects expression, like `(X13|R3)`, would usually also occur in the fixed-effects specification.  The (conditional) distribution of the random effects is assumed to have mean zero and any non-zero mean gets incorporated in the fixed-effects.

**Comment by marynavickt** [comment]
I was able to reproduce the same error on a different dataset so I can openly share it. Probably you could help me figuring out the cause?

Formula that I used: PRICE ~ SQUARE+ (GBA|ASSESSMENT_NBHD)+(LANDAREA|CENSUS_TRACT)

As for data types: ASSESSMENT_NBHD and CENSUS_TRACT was made categorical, GBA, LANDAREA, SQUARE and PRICE  numerical.

The error is still the same: MethodError: no method matching rankUpdate!(::Hermitian{Float64,Array{Float64,2}}, ::BlockedSparse{Float64,Int32}, ::Float64)
Closest candidates are:
  rankUpdate!(::Union{Hermitian{T<:Union{Float32, Float64},S<:(Union{DenseArray{T,2}, ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Tuple{AbstractUnitRange,Vararg{Any,N} where N} where ......

Dataset:
[DC_Properties_example.csv.zip](https://github.com/dmbates/MixedModels.jl/files/2726484/DC_Properties_example.csv.zip)

**Comment by dmbates** [comment]
Thanks for the data set.  I will add that method.  My comments in #153 about the formula still hold.

**Comment by dmbates** [comment]
@marynavickt Could you check that the master branch works on your example now and then I will release a new version of the package?

One way to switch to the master branch is
```
julia> using Pkg; Pkg.develop("MixedModels")
```
before any `using MixedModels` statements.

Once a new version is released you should be able to get the new release with
```
julia> using Pkg; Pkg.free("MixedModels"); Pkg.update()
```

**Comment by dmbates** [comment]
@marynavickt Could you try again after `git pull` in the `~/.julia/dev/MixedModels` directory, please?
