### ISSUE TITLE
Different syntax for fitting the models. What's the difference?

### ISSUE THREAD

**Issue by skanskan** [dmbates/MixedModels.jl#159]
Hello.

I would like to use MixedModels.jl to fit regression models with random effects.   
Looking at the official docs and some examples on the Internet I've found different syntaxes.    

For example if I want to fit a Logit model (my outcome is binary) I can do it...:

```
fit(GeneralizedLinearMixedModel, @formula(y ~ 1 + x + (1 | id)), df, Bernoulli())
fit!(glmm(@formula(y ~ 1 + x + (1 | id)), df, Binomial(), LogitLink()))
```

What's the difference between both syntaxes?

**Comment by palday** [comment]
@skanskan This should work in the current release.
