### ISSUE TITLE
calculating bootstrap confidence intervals

### ISSUE THREAD

**Issue by jen265** [dmbates/MixedModels.jl#172]
I tried to calculate boostrap confidence intervals for my linear mixed effects model (name: fm1) with MixedModels.jl using the syntax below (for simplicity, I dropped 8 predictors). Unfortunately, printing "bootstrap(10000, fm1)" displays the fixed effects in a random order, which makes it impossible to calculate the confidence interval for a specific fixed effect. Is it possible that printing "bootstrap(10000, fm1)" displays the fixed effects in the order they appear in the mixed model?
Any help is very much appreciated.

modbstp = bootstrap(10000, fm1);
print(names(modbstp))
ci_intercept = percentile(modbstp[:β01], [2.5, 97.5])
ci_agr = percentile(modbstp[:β02], [2.5, 97.5])
ci_cns = percentile(modbstp[:β03], [2.5, 97.5])

**Comment by palday** [comment]
Bootstrap will change a bit when #202 lands. You can try out the new functionality by installing that branch:
```julia
# get here by typing the right square bracket at the julia prompt
# get out of here by backspacing on an empty line
pkg> add MixedModels#bootstraptuples 
```
And if you want to go back to the main release:
```julia
pkg> free MixedModels
```
