### ISSUE TITLE
wt argument issue

### ISSUE THREAD

**Issue by jpadams16** [dmbates/MixedModels.jl#189]
Hi,

Model fitting does not appear to work when including the 'wt' argument. I receive the error, "MethodError: no method matching...". When the wt argument is removed the model does successfully fit.

I'm using the following example code.

model = fit!(GeneralizedLinearMixedModel(@formula(event ~ 1 + var1 * var2 + var3 + (1|var4)), dt, Bernoulli(), wt=dt[:weights]), fast=true)

Cheers.

**Comment by Nosferican** [comment]
I believe that was changed to `wts` to match with GLM.jl. The deprecation, might need to be released as a patch.
Could you post the a minimal reproducible example?
Try,
```
model = fit(MixedModel(@formula(event ~ 1 + var1 * var2 + var3 + (1|var4)),
                   dt,
                   Bernoulli(),
                   wts = dt[:weights],
                   fast = true)
```

**Comment by dmbates** [comment]
Can we close this issue now?

**Comment by Nosferican** [comment]
I think so... If anyone else has the issue maybe we can add the deprecation and add support for the old syntax.
