### ISSUE TITLE
Documentation out-dated

### ISSUE THREAD

**Issue by andyreagan** [dmbates/MixedModels.jl#191]
The line:

> This model cannot be fit in v"2.0.0". Watch for updates.

in the optimization doc is outdated, since we're on version > 2 by now.

<img width="733" alt="Screen Shot 2019-09-16 at 12 01 07 PM" src="https://user-images.githubusercontent.com/3012361/64973871-cb99af80-d879-11e9-89e9-2f357c473db5.png">

**Comment by dmbates** [comment]
@andyreagan Could you please check the `dev` branch of the documentation and see if the explanation there is sufficient?  I can release a new version with the `zerocorr!` function and the new documentation to fit the model you indicated.  However, I would prefer to wait a couple of days as I will have more changes to incorporate in a new version.

**Comment by andyreagan** [comment]
You can release the updated docs whenever, by me.

I was simply pointing out because these little notes are easy to forget about and by the looks, it had been forgotten.

**Comment by andyreagan** [comment]
The note looks the same on the `dev` branch of the docs

**Comment by palday** [comment]
Note that there are two issues here: 

1. the overly specific version reference, which is outdated, but which seems pointless to update given ...
2. the new functionality for zero correlation in the dev version and its associated syntax.

I'll update the docs to fix this.
