### ISSUE TITLE
How to cite MixedModels.jl?

### ISSUE THREAD

**Issue by skanskan** [dmbates/MixedModels.jl#192]
Hello.

How should we cite MixedModels.jl in an article or thesis?
I mean a BibTeX code with the authors, title...

**Comment by nalimilan** [comment]
Could use Zenodo, just like we recently did in GLM (https://github.com/JuliaStats/GLM.jl/pull/331). @dmbates What's your take on this?

Cc: @Nosferican

**Comment by Nosferican** [comment]
Aye. I cited this package recently in a proceedings and used the Zenodo generated `.bib` file. If using the Zenodo DOI you should get something like,
```
@misc{MixedModels.jl,
      author = {Bates, Douglas  and
	        Santiago Calderón, José Bayoán and
		Kleinschmidt, Dave and
		Kelman, Tony and
		Babayan, Simon and
		Mogensen, Patrick Kofod and
		Piibeleht, Morten and
		Bouchet-Valat, Milan and
		Hatherly, Michael and
		Saba, Elliot and
		Baldassari, Antoine and
		Noack, Andreas},
      title = {{MixedModels.jl}},
      year = 2013,
      url = {https://github.com/dmbates/MixedModels.jl},
      doi = {10.5281/zenodo.596435}
}
```
I prefer to cite the all versions unless it refers to a specific version I used for generating some output (then the `year` and `doi` change). Even so, that information should be available from the `Manifest.toml` in the application.

**Comment by nalimilan** [comment]
Woops, I hadn't realized that Zenodo was already enabled. Then maybe nothing is needed?

**Comment by Nosferican** [comment]
If @skanskan, thinks that seems like an acceptable answer we could close the issue. I don't think we need an additional mention in the documentation since the README has the citation shield, but maybe we could entertain a PR for it in the docs. I will close the the issue in a couple days unless there are any objections.
