### ISSUE TITLE
How to obtain predicted values or residuals of MixedModels in Julia?

### ISSUE THREAD

**Issue by mammask** [dmbates/MixedModels.jl#34]
Hi,

I am currently fitting a linear mixed effects model in Julia and I am trying to obtain the predicted values or residuals. Is there a straightforward way to achieve it?

Any assistance is appreciated.

Thanks,

Kostas

**Comment by mammask** [comment]
Found it. I should search more before posting. In the code .resid is the solution.

**Comment by JonnyCBB** [comment]
Is this an array of the residuals? I can't find it. Can you help me? Thanks

**Comment by DarioSarra** [comment]
This doesn't work anymore I think. What is the current solution?
