### ISSUE TITLE
Crash in 0.5 - chksquare not defined

### ISSUE THREAD

**Issue by protogeezer** [dmbates/MixedModels.jl#38]
it appears that Base.LinAlg.chksquare => Base.LinAlg.checksquare

julia> fm = fit!(lmm(math_gr_8 ~ 1 + math_gr_5 + math_gr_3 + reading_gr_5 + reading_gr_3 +  
           (1 + math_gr_5 + math_gr_3 | class_id),df))
ERROR: UndefVarError: chksquare not defined
 in getindex at /Users/sjbespa/.julia/v0.5/MixedModels/src/paramlowertriangular.jl:11
 in anonymous at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:89
 in _mapreduce at reduce.jl:141
 in mapreduce at reduce.jl:159
 [inlined code] from reduce.jl:162
 in call at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:89
 in lmm at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:105
 in eval at /usr/local/lib/julia/sys-debug.dylib

**Comment by dmbates** [comment]
I have a fix for this in the https://github.com/dmbates/MixedModels.jl/tree/glmms branch.  You also need to incorporate  https://github.com/dcjones/Showoff.jl/pull/9 for the `Showoff` package to work with version 0.5-.

I'll wait to see if @dcjones will incorporate that fix by @keno before trying to release a version of `MixedModels` for Julia 0.5-
