### ISSUE TITLE
Covariance structure, penalized splines?

### ISSUE THREAD

**Issue by kkmann** [dmbates/MixedModels.jl#39]
Hey,

I am glad to see that mixed models are coming to Julia. 

Are there any plans for allowing the specification of a parametric covariance model? This would be very helpful for analyzing longitudinal data. Also, it would be very nice to have a way of directly fitting penalized smooth splines (GAM) with a unified interface. How complicated would that be?

**Comment by dmbates** [comment]
@kkmann I don't have plans for allowing the specification of a parameteric covariance model.  I am one of the authors of the nlme and of the [lme4](https://github.com/lme4/lme4) packages for R.  The nlme package allowed for a parametric covariance model which ultimately I found to be more confusing than illuminating.  I prefer the "do one thing and do it well" approach that we used in lme4 and now in this package.

Adding GAM models would be difficult and I don't have plans to do so soon.  The increase in complexity when you start allowing all different sorts of options, especially in a language like Julia, gets to be difficult to handle well.  Getting to a cleaner design of a language is one of the reasons I prefer Julia to R.

The main advantages that this package offers compared to the lme4 package for R is speed and reliability.  We have several instances where fitting a model with lmm is a couple of orders or magnitude faster than with lmer for R.   To those fitting models to large data sets this is important.  I don't want to compromise the speed by including dozens of optional specifications.
