### ISSUE TITLE
Residuals

### ISSUE THREAD

**Issue by carlosfamilia** [dmbates/MixedModels.jl#50]
In terms of model diagnostics, what diagnostics can be run for these models? Are the residuals an option to this, and if so, how can we define the residuals? 
As Douglas said:
"As for residuals, like many other properties of mixed-effects models, you need to be careful how you define them.  You need to decide if the random effects are included in the fitted values or not. Perhaps it is better to define a fitted method for LinearMixedModel, which can then be the basis of a residuals method."

**Comment by JonnyCBB** [comment]
Any news on this?

**Comment by dmbates** [comment]
I have added `fitted` and `residuals` methods for `LinearMixedModels` in #62 

These are defined using the fixed-effects and all the random effects for `fitted` and `residuals` is simply the difference between `model_response(m)` and `fitted(m)`.  So I am taking the simplest approach here.

**Comment by JonnyCBB** [comment]
Thanks. This is great.
