### ISSUE TITLE
Crash with latest MixedModels and v0.5.0-rc3...

### ISSUE THREAD

**Issue by protogeezer** [dmbates/MixedModels.jl#54]
Using the VAM model (admittedly malformed - and run by mistake):
df = read_scores("ecls.k8.balanced.csv");
	mixed = lmm(math_gr_8 ~ math_gr_5 + math_gr_3 + reading_gr_5 + reading_gr_3 + (1 + math_gr_5 + math_gr_3 + reading_gr_5 + reading_gr_3 |school_id) + (1 + math_gr_5 + math_gr_3 + reading_gr_5 + reading_gr_3 |class_id),df);
fit!(mixed)

results in:
julia> fit!(mixed);
in callback catch
ERROR: MethodError: no method matching A_mul_B!(::Base.ReshapedArray{Float64,2,SubArray{Float64,1,Array{Float64,1},Tuple{UnitRange{Int64}},true},Tuple{}}, ::LowerTriangular{Float64,Array{Float64,2}})
Closest candidates are:
  A_mul_B!(::AbstractArray{T,2}, ::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, ::Tridiagonal{T}) at linalg/triangular.jl:382
  A_mul_B!(::AbstractArray{T,2}, ::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, ::Union{Bidiagonal{T},SymTridiagonal{T},Tridiagonal{T}}) at linalg/bidiag.jl:282
  A_mul_B!(::AbstractArray{T,2}, ::Base.LinAlg.AbstractTriangular{T,S<:AbstractArray{T,2}}, ::Union{AbstractArray{T,1},AbstractArray{T,2}}) at linalg/triangular.jl:385
  ...
 in tscale!(::SparseMatrixCSC{Float64,Int64}, ::LowerTriangular{Float64,Array{Float64,2}}) at /Users/sjbespa/.julia/v0.5/MixedModels/src/paramlowertriangular.jl:153
 in cfactor!(::MixedModels.LinearMixedModel{Float64}) at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:158
 in (::MixedModels.#obj#16{MixedModels.LinearMixedModel{Float64}})(::Array{Float64,1}, ::Array{Float64,1}) at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:190
 in nlopt_callback_wrapper(::UInt32, ::Ptr{Float64}, ::Ptr{Float64}, ::Ptr{Void}) at /Users/sjbespa/.julia/v0.5/NLopt/src/NLopt.jl:427
 in optimize!(::NLopt.Opt, ::Array{Float64,1}) at /Users/sjbespa/.julia/v0.5/NLopt/src/NLopt.jl:526
 in fit!(::MixedModels.LinearMixedModel{Float64}, ::Bool, ::Symbol) at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:207
 in fit!(::MixedModels.LinearMixedModel{Float64}) at /Users/sjbespa/.julia/v0.5/MixedModels/src/pls.jl:179

It wouldn't be hard to send you the file with the data frame.... if that would help (with instructions on where to send/upload it)...

**Comment by dmbates** [comment]
@protogeezer Yes, I would appreciate it if you could provide me with the data to test this out.  Could you [email me](mailto:dmbates@gmail.com), so I can get your email address and allow you access to a directory on [Box](https://box.com)
