### ISSUE TITLE
What should I cite when using MixedModels?

### ISSUE THREAD

**Issue by mmagnuski** [dmbates/MixedModels.jl#60]
Thanks for `MixedModels.jl` - great package!
What is your preferrence for citation in a research paper?

**Comment by dmbates** [comment]
You're welcome.  Thanks for the acknowledgement.

I'm not entirely sure how to cite the package.  Let me ask about it on the julia-dev mailing list.

**Comment by mmagnuski** [comment]
I can refer to one of your papers (whichever you prefer) and give github URL to MixedModels.jl + version tag if it is less problematic.

**Comment by kleinschmidt** [comment]
How about adding something like [zenodo](https://guides.github.com/activities/citable-code/) to the repository? Then there will be a DOI associated with each release automatically.

**Comment by dmbates** [comment]
I have set up `zenodo` for this repository.  I am just in the throes of trying a release out.  There are too many moving parts right now in DataFrames, DataArrays, CategoricalArrays, NullableArrays and all that.

**Comment by dmbates** [comment]
There is now a DOI on the README,  Currently its value is [![DOI](https://zenodo.org/badge/9106942.svg)](https://zenodo.org/badge/latestdoi/9106942) for the 0.6.0 release of `MixedModels`.

**Comment by mmagnuski** [comment]
MixedModels.jl seem to be submitted to zenodo as a data set, is this correct?

**Comment by dmbates** [comment]
It's a zip file of that particular release of the package.  In other words it is the sources that are specific to a release of the package.  Does that make sense?

**Comment by mmagnuski** [comment]
Ah, ok, I never used zenodo and I thought it should be mentioned as software in the citation snippet they generate. Thanks!
