### ISSUE TITLE
uncorrelated random slope and intercept, with nested levels

### ISSUE THREAD

**Issue by kaskarn** [dmbates/MixedModels.jl#74]
Hello,

Brief backstory: participants are nested in centers. two participants in my dataset changed center during the course of the study. Analysis on the full sample can be carried out using a crossed-effects model, which we specify as: 

Y ~ ... + (1 | center)  + (0 + x | center) + (1 | pid)

This works fine in both lme4 and MixedModels.

However, when we remove both center-switching participants, the dataset suddenly has a neatly nested structure and MixedModels throws an error caused by the lack of a !downdate(Diagonal, Sparse Matrix, Sparse Matrix) method.

The same model still converges happily in lme4

**Comment by dmbates** [comment]
I am working on a refactoring of the code to handle uncorrelated random effects for the same grouping factor more effectively.  It's still a work in progress.

**Comment by kaskarn** [comment]
Ok, thanks for the hard work! Let me know if/where you could use the help

**Comment by dmbates** [comment]
The master branch now has this capability.  I'm just waiting for the Travis tests to finish before creating a new release.
