### ISSUE TITLE
FR: significance for variance

### ISSUE THREAD

**Issue by ohadle** [dmbates/MixedModels.jl#81]
The current fit function returns several parameters for the model. For example, following https://github.com/dmbates/MixedModelsinJulia/blob/master/SimpleLMM.ipynb:
```julia
Linear mixed model fit by maximum likelihood
 Formula: Y ~ 1 + (1 | G)
   logLik   -2 logLik     AIC        BIC    
 -163.66353  327.32706  333.32706  337.53065

Variance components:
              Column    Variance  Std.Dev. 
 G        (Intercept)  1388.3335 37.260347
 Residual              2451.2500 49.510100
 Number of obs: 30; levels of grouping factors: 6

  Fixed-effects parameters:
             Estimate Std.Error z value P(>|z|)
(Intercept)    1527.5   17.6946  86.326  <1e-99
```

Would it be possible to also return a p-value for the variance estimator of the random effect parameter (G)?

**Comment by dmbates** [comment]
Short answer: no.

Longer answer: it is a very tricky idea.  As with most p-value calculations, the first thing you should ask yourself is "do I need this?" and, for the most part, the answer is no.  It is much more effective to determine some sort of confidence interval on the parameter of interest, as is shown later in that document.

If the need for a p-value is external (journal editors or referees insisting on such a number, despite its being meaningless) for a simple model I would use the bootstrap function and calculate the proportion of bootstrap parameter estimates that very small.  See the examples later in that document.  For more complex models you might try fitting a reduced model (i.e. a model without the random effect) and use a likelihood ratio test.  The problem with that approach is what to use for the reference distribution for the change in deviance.

The thing not to do is to use some quadratic approximation to the log-likelihood at the parameter estimates and assume asymptotic normality as is done in SAS PROC MIXED and in the SPSS mixed procedure.  It is an absurd oversimplification of the actual situation but that doesn't stop these companies from pedalling such nonsense.

**Comment by ohadle** [comment]
Thank you for the detailed answer!
