### ISSUE TITLE
Avoid extending Base methods on Base types

### ISSUE THREAD

**Issue by tkelman** [dmbates/MixedModels.jl#85]
This package has been guilty of this for a while apparently, and you did just clean up a whole bunch of these with the `*_mul_*` methods. The ones I still see are `Ac_ldiv_B!`, `A_rdiv_B!`, and `A_rdiv_Bc!` here https://github.com/dmbates/MixedModels.jl/blob/82b7bffc4ce10dc3cb98360ff7926e3a69c23cf9/src/linalg.jl#L86-L151. Would be a good medium-term goal to avoid the type piracy here. Base's method tables are global, so extending these can change behavior of other unrelated code depending on whether or not MixedModels has been imported.

**Comment by dmbates** [comment]
I do plan on creating a PR to add those `_*div_` methods to Base.  Thanks for the reminder.

**Comment by tkelman** [comment]
Cool. Are there three-argument versions that would work, where you specify the destination separately? The inconsistency of whether the two-argument mutating versions of these modifies the first argument or the second argument depending on the input types bothers me a bit, but that's a Base problem.

**Comment by dmbates** [comment]
Apparently not.  In v0.6.0-rc2
```
julia> B = ones(2,2)
2×2 Array{Float64,2}:
 1.0  1.0
 1.0  1.0

julia> A = Diagonal(ones(2))
2×2 Diagonal{Float64}:
 1.0   ⋅
  ⋅   1.0

julia> @which Ac_ldiv_B!(B, A, B)
ERROR: no method found for the specified argument types
Stacktrace:
 [1] which(::Any, ::Any) at ./reflection.jl:824

julia> @which A_ldiv_B!(B, A, B)
ERROR: no method found for the specified argument types
Stacktrace:
 [1] which(::Any, ::Any) at ./reflection.jl:82
```

**Comment by tkelman** [comment]
Did this get backported to Compat, or is the package still doing it?
