### ISSUE TITLE
Discrepancy in loglikelihoods between R/lmer and MixedModels.jl/lmm when weights is used

### ISSUE THREAD

**Issue by lmwang9527** [dmbates/MixedModels.jl#89]
I am evaluating switching from R/lme4 to MixedModels.jl for its superior speed. I am getting very different log-likelihoods for models estimated using these two packages when weights is provided (the log-likelihoods are identical when no weights is used). Any insights what may explain the discrepancy? Thanks!

Below is the code that produces the phenomenon:

```
##R
library(lme4)
set.seed(1)
wts <- runif(nrow(mtcars), 0, 30)
mtcars$wts <- wts

lmm_rw <- lmer(mpg ~ wt  + (wt | vs), mtcars, weights=wts, REML=FALSE)
lmm_r  <- lmer(mpg ~ wt  + (wt | vs), mtcars, REML=FALSE)
logLik(lmm_rw); logLik(lmm_r)
#'log Lik.' -83.43746 (df=6)
#'log Lik.' -76.69613 (df=6)

write.csv(mtcars, "./mtcars.csv")
```

```
##julia
using DataFrames
using MixedModels
mtcars = readtable("./mtcars.csv");
wts = convert(Array, mtcars[:wts]);

lmm_w = fit!(lmm(@formula(mpg ~ wt + (wt | vs)), mtcars, weights=wts))
lmm_r = fit!(lmm(@formula(mpg ~ wt + (wt | vs)), mtcars))
loglikelihood(lmm_w)
#-123.013855036427
loglikelihood(lmm_r)
#-76.69613038651636
```

**Comment by dmbates** [comment]
Thank you for including a reproducible example.

I failed to include a term that depends on the weights in the objective function.  A fix for this should be available later today.

This term is a constant and does not affect the location of the parameter estimates, it simply changes the value of the loglikelihood as you indicate.

As an aside, the [`RCall`](https://github.com/JuliaStats/RCall.jl) package makes it easy to compare results from `R` and `Julia`.
```julia
julia> using DataFrames, MixedModels, RCall

julia> R"set.seed(1); mtcars$wts <- wts <- runif(nrow(mtcars), 0, 30)"
RCall.RObject{RCall.RealSxp}
 [1]  7.965260 11.163717 17.185601 27.246234  6.050458 26.951691 28.340258
 [8] 19.823934 18.873421  1.853588  6.179237  5.296703 20.610685 11.523112
[15] 23.095243 14.930977 21.528555 29.757183 11.401055 23.323357 28.041157
[22]  6.364276 19.550213  3.766653  8.016620 11.583423  0.401710 11.471639
[29] 26.090725 10.210470 14.462403 17.986975


julia> R"logLik(lmer(mpg ~ wt + (wt|vs), mtcars, REML=FALSE))"
RCall.RObject{RCall.RealSxp}
'log Lik.' -76.69613 (df=6)


julia> @rget mtcars;

julia> loglikelihood(fit!(lmm(@formula(mpg ~ 1 + wt + (1+wt|vs)), mtcars, weights=Array(mtcars[:wts]))))
-123.01385503642763
```

**Comment by lmwang9527** [comment]
Thanks for fixing the issue so quickly and for the tip for running R code from julia; I appreciate it!
